### PR TITLE
fix: remove mutable default args in generate_machine_deployments_for_…

### PR DESCRIPTION
**Pull request by okozachenko1203**
…cluster

fix https://github.com/vexxhost/magnum-cluster-api/issues/339

### CODE REVIEW

**Comment by mnaser** [comment]
@okozachenko1203 please create functional tests to handle this.

The best idea to test the functional tests locally is by simply creating a kind cluster, then install capi/capo (use the scripts in hack/) and look at Jenkinsfile.

**Comment by okozachenko1203** [comment]
> @okozachenko1203 please create functional tests to handle this.
> 
> The best idea to test the functional tests locally is by simply creating a kind cluster, then install capi/capo (use the scripts in hack/) and look at Jenkinsfile.

I think the only functional test scenario for this issue is the cluster upgrade because `generate_machine_deployments_for_cluster` is only called when a cluster is created and upgraded.

let me add another step in `hack/run-functional-tests.sh` file for this upgrade scenario

**Comment by okozachenko1203** [comment]
so the functional test steps will be as following;
- create a cluster using `kube_tag_old`
- do sonobuoy test
- upgrade the cluster to `kube_tag_new`
- do sonobuoy test

This will take very long time. what do you think if we just run sonobuoy smoke tests? it will speed up

**Comment by mnaser** [comment]
@okozachenko1203 I meant in here actually sorry

https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/tests/functional/test_driver.py

**Comment by mnaser** [comment]
Replaced by #349

**Pull request closed without merging**
