### PR TITLE
Use up-to-date provisioner name for Cinder CSI

### PR DESCRIPTION
**Pull request by nguyenhuukhoi**
Change Cinder CSI Provisioner 

from

"provisioner": "kubernetes.io/cinder"

to

"provisioner": "cinder.csi.openstack.org",

### CODE REVIEW

**Comment by ngyenhuukhoi** [comment]
Use up-to-date provisioner name for Cinder CSI

**Comment by mnaser** [comment]
Hi @nguyenhuukhoi -- I noticed you reverted your commit so the PR is empty, did you mean to do that? :)

**Comment by nguyenhuukhoi** [comment]
> Hi @nguyenhuukhoi -- I noticed you reverted your commit so the PR is empty, did you mean to do that? :)

Sorry. I updated my PR.

**Comment by mnaser** [comment]
thanks for the contribution @nguyenhuukhoi !  your code is officially in, we'll cut a release soon hopefully and it will be available ✨

**Pull request merged**
