### PR TITLE
feat: Support Flatcar OS

### PR DESCRIPTION
**Pull request by stefan-chivu**
Based on: https://github.com/vexxhost/magnum-cluster-api/pull/44

Adapted the aforementioned PR to contain the right ignition config and also modified the secret type used for the CA cert secret.

CAPI expects a CA secret of type "cluster.x-k8s.io/secret" instead of "kubernetes.io/tls". Also, the "cluster.x-k8s.io/cluster-name" label has been added for the secret resource, containing the cluster's stack id.

### CODE REVIEW

**Comment by mnaser** [comment]
sadly it died on me right while i was debugging, but i was able to get into vnc using ngrok and found that it was complaining about an invalid/incorrect pound sign in the ignition config so it just died (`#`).

i'm restarting but this time i'll try to pull out the config it generated.

**Comment by mnaser** [comment]
image

**Comment by mnaser** [comment]
ok, for some reason, it's getting plain ignition.. hold on...

**Comment by stefan-chivu** [comment]
> ok, for some reason, it's getting plain ignition.. hold on...

Out of curiosity, what does it get?

**Comment by mnaser** [comment]
https://github.com/vexxhost/magnum-cluster-api/pull/225/commits/5f7c715ce95ced1337dc0b4e03e71bb3eeb00f82#diff-b74064dc7fb33b2c4232e9a38c8df0f8c59e996507abeb15478b0973e2e0a2d1R47

cloud-init, but that my bad :)

**Comment by mnaser** [comment]
success!  it's just running sonobuoy now, if it's all good (which i believe it will be), i'll push up a later patch which will add the matrix back and will be able to merge this today.

**Pull request merged**
