### PR TITLE
Kubernetes 1.28.x support

### PR DESCRIPTION
**Pull request by 0x00ace**
@mnaser 
You can safely merge this - it will add only support for k8s 1.28.x
With k8s 1.28.x there is no issues with keystone auth

### CODE REVIEW

**Comment by mnaser** [comment]
@0x00ace I'm picking this branch up from your side to wrap up real quick )

**Comment by mnaser** [comment]
@0x00ace ok, made some changes that will even work with v1.28 now and add testing, I made rockylinux non voting because it is failing often.

@0x00ace since you contributed rocky support, do you use it both with 8 and 9?  I want to try and fix up capo-image-elements to build rockylinux images for you but want to know where to spend my time, so we can have reliable rocky tests :)

**Comment by mnaser** [comment]
Looks like Cilium is broken with those images, working on testing it here and will push fix shortly.

**Comment by mnaser** [comment]
https://github.com/vexxhost/capo-image-elements/pull/3

**Comment by mnaser** [comment]
I'm working on making Rocky voting again @0x00ace to not make a waste of your effort:

https://github.com/vexxhost/capo-image-elements/pull/4

I will merge this for now however, thank you for your efforts.

**Comment by 0x00ace** [comment]
@mnaser 
I'm using Rocky 9.
Also, I have made cilium to work, and have no problem with cilium patches from the main branch. I had just added cilium helm chart to the vendor dir and removed it from gitignore.

**Comment by mnaser** [comment]
Can you see the PR in capo image elements and see if you can help with that if you don't mind?

We're hoping to move to building with that. It's so much faster and more reliable.

**Comment by 0x00ace** [comment]
> Can you see the PR in capo image elements and see if you can help with that if you don't mind?
> 
> We're hoping to move to building with that. It's so much faster and more reliable.

Yes, I understand that we are trying to migrate to a new way of image creation. I need some time to deep dive on how it's working and will try it out.

**Pull request merged**
